---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - pull_request

steps:
  - name: database healthcheck
    image: 'postgres:16.0-alpine'
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    commands:
      - while ! pg_isready; do sleep 1; done

  - name: restore cache
    image: 'meltwater/drone-cache:v1.4.0'
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_user
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_password
    settings:
      archive_format: gzip
      bucket: trainlog-cache
      cache_key: '{{ .Repo.Name }}-{{ checksum ".tool-versions" }}-{{ checksum "mix.lock" }}'
      endpoint: minio:9000
      mount:
        - _build
        - deps
      path_style: true
      region: us-east-1
      restore: true

  - name: test
    image: 'elixir:1.15.4-slim'
    environment:
      MIX_ENV: test
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
    commands:
      - mix do local.rebar --force, local.hex --force, deps.get, deps.compile
      - mix compile
      - mix test --cover --trace --slowest 10

  - name: lint
    image: 'elixir:1.15.4-slim'
    commands:
      - mix do local.rebar --force, local.hex --force, deps.get, deps.compile
      - mix compile
      - mix format --check-formatted
      - mix credo suggest --strict --format=flycheck
      - mix dialyzer --no-check --quiet --ignore-exit-status --format short

  - name: rebuild cache
    image: 'meltwater/drone-cache:v1.4.0'
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: minio_user
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_password
    settings:
      archive_format: gzip
      bucket: trainlog-cache
      cache_key: '{{ .Repo.Name }}-{{ checksum ".tool-versions" }}-{{ checksum "mix.lock" }}'
      endpoint: minio:9000
      exit_code: true
      mount:
        - _build
        - deps
      path_style: true
      rebuild: true
      region: us-east-1

services:
  - name: db
    image: 'postgres:16.0-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
