---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - pull_request

steps:
  - name: database healthcheck
    image: 'postgres:14.2-alpine'
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
    commands:
      - while ! pg_isready; do sleep 1; done
  - name: test
    image: 'elixir:1.13.4'
    environment:
      MIX_ENV: test
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
    commands:
      - mix do local.rebar --force, local.hex --force, deps.get, deps.compile
      - mix test --cover --trace --slowest 10

services:
  - name: db
    image: 'postgres:14.2-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
