---
version: '3.7'

services:
  db:
    image: 'postgres:15.3-alpine'
    hostname: &db_host db
    init: true
    environment:
      POSTGRES_USER: &db_user postgres
      POSTGRES_PASSWORD: &db_pass postgres
      POSTGRES_DB: &db_name postgres
    volumes:
      - './priv/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'db_data:/var/lib/postgresql/data'
    restart: unless-stopped
  app:
    image: 'elixir:1.14.5'
    hostname: app
    depends_on:
      - db
    init: true
    environment:
      POSTGRES_HOST: *db_host
      POSTGRES_USER: *db_user
      POSTGRES_PASS: *db_pass
      POSTGRES_NAME: wabanex_dev
    volumes:
      - '.:/opt/app'
      - 'app_build:/opt/app/_build'
      - 'app_deps:/opt/app/deps'
    working_dir: /opt/app
    restart: unless-stopped
    entrypoint: sleep
    command: infinity

volumes:
  db_data: {}
  app_build: {}
  app_deps: {}
