---
version: '3.7'
services:
  db:
    image: 'postgres:13.3-alpine'
    hostname: &db_host db
    environment:
      POSTGRES_USER: &db_user postgres
      POSTGRES_PASSWORD: &db_pass postgres
      POSTGRES_DB: &db_name postgres
    volumes:
      - './priv/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'db_data:/var/lib/postgresql/data'
    restart: unless-stopped
volumes:
  db_data: {}
